<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
        <AssemblyOriginatorKeyFile>Andrey Kosinets_0x13823130_public.asc</AssemblyOriginatorKeyFile>
        <PublicSign>false</PublicSign>
        <ApplicationIcon>telegramstatusicon.ico</ApplicationIcon>
        <UserSecretsId>408129bc-43fe-4397-b33b-d86bdb8a1b77</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hqub.Last.fm" Version="2.5.1" />
        <PackageReference Include="ImprovedСonsole" Version="1.1.6" />
        <PackageReference Include="KM.Yandex.Music.Api" Version="2.0.6" />
        <PackageReference Include="KM.Yandex.Music.Client" Version="2.0.6" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="SpotifyAPI.Web" Version="7.4.2" />
        <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.4.2" />
        <PackageReference Include="StarkSoftProxy" Version="1.6.0" />
        <PackageReference Include="WTelegramClient" Version="4.4.3" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="..\..\..\..\..\Users\andru\.nuget\packages\km.yandex.music.api\2.0.6\contentFiles\any\net8.0\README.md" />
      <Content Remove="..\..\..\..\..\Users\andru\.nuget\packages\km.yandex.music.client\2.0.6\contentFiles\any\net8.0\README.md" />
    </ItemGroup>

</Project>
